// Code generated by protoc-gen-go. DO NOT EDIT.
// source: card.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	card.proto
	card_common.proto
	card_order.proto

It has these top-level messages:
	GetCardRequest
	GetCardReply
	GetCardListRequest
	GetCardListReply
	CreateCardRequest
	CreateCardReply
	ModifyCardInformation
	ModifyCardRequest
	ModifyCardReply
	CardInformation
	ItemInformation
	ItemCouponInformation
	ItemGoodsInformation
	RemoveCardRequest
	RemoveCardReply
	SetCardItemsRequest
	SetCardItemsReply
	SetCardStatusRequest
	SetCardStatusReply
	GetUserCardListRequest
	GetUserCardListReply
	UserCard
	Error
	CreateOrderRequest
	CreateOrderReply
	FinishOrderRequest
	FinishOrderReply
	Order
	GetOrderRequest
	GetOrderReply
	GetOrderListRequest
	GetOrderListReply
	TimeRange
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CardStatus int32

const (
	CardStatus_All    CardStatus = 0
	CardStatus_Unused CardStatus = 1
	CardStatus_Inuse  CardStatus = 2
)

var CardStatus_name = map[int32]string{
	0: "All",
	1: "Unused",
	2: "Inuse",
}
var CardStatus_value = map[string]int32{
	"All":    0,
	"Unused": 1,
	"Inuse":  2,
}

func (x CardStatus) String() string {
	return proto.EnumName(CardStatus_name, int32(x))
}
func (CardStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetCardRequest struct {
	CardId uint64 `protobuf:"varint,1,opt,name=cardId" json:"cardId,omitempty"`
	ShopId uint64 `protobuf:"varint,2,opt,name=shopId" json:"shopId,omitempty"`
}

func (m *GetCardRequest) Reset()                    { *m = GetCardRequest{} }
func (m *GetCardRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCardRequest) ProtoMessage()               {}
func (*GetCardRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetCardRequest) GetCardId() uint64 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *GetCardRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type GetCardReply struct {
	Err             *Error           `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	CardInformation *CardInformation `protobuf:"bytes,2,opt,name=cardInformation" json:"cardInformation,omitempty"`
}

func (m *GetCardReply) Reset()                    { *m = GetCardReply{} }
func (m *GetCardReply) String() string            { return proto.CompactTextString(m) }
func (*GetCardReply) ProtoMessage()               {}
func (*GetCardReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetCardReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GetCardReply) GetCardInformation() *CardInformation {
	if m != nil {
		return m.CardInformation
	}
	return nil
}

type GetCardListRequest struct {
	ShopId         uint64     `protobuf:"varint,1,opt,name=shopId" json:"shopId,omitempty"`
	Status         CardStatus `protobuf:"varint,2,opt,name=status,enum=card.pkg.rpc.protos.CardStatus" json:"status,omitempty"`
	Page           uint64     `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	PageSize       uint64     `protobuf:"varint,4,opt,name=pageSize" json:"pageSize,omitempty"`
	WithItemDetail bool       `protobuf:"varint,5,opt,name=withItemDetail" json:"withItemDetail,omitempty"`
}

func (m *GetCardListRequest) Reset()                    { *m = GetCardListRequest{} }
func (m *GetCardListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCardListRequest) ProtoMessage()               {}
func (*GetCardListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetCardListRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *GetCardListRequest) GetStatus() CardStatus {
	if m != nil {
		return m.Status
	}
	return CardStatus_All
}

func (m *GetCardListRequest) GetPage() uint64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCardListRequest) GetPageSize() uint64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetCardListRequest) GetWithItemDetail() bool {
	if m != nil {
		return m.WithItemDetail
	}
	return false
}

type GetCardListReply struct {
	Err                 *Error             `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	CardInformationList []*CardInformation `protobuf:"bytes,2,rep,name=cardInformationList" json:"cardInformationList,omitempty"`
	Count               uint64             `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
}

func (m *GetCardListReply) Reset()                    { *m = GetCardListReply{} }
func (m *GetCardListReply) String() string            { return proto.CompactTextString(m) }
func (*GetCardListReply) ProtoMessage()               {}
func (*GetCardListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetCardListReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GetCardListReply) GetCardInformationList() []*CardInformation {
	if m != nil {
		return m.CardInformationList
	}
	return nil
}

func (m *GetCardListReply) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CreateCardRequest struct {
	ShopId          uint64 `protobuf:"varint,1,opt,name=shopId" json:"shopId,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description     string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	BackgroundImage string `protobuf:"bytes,4,opt,name=backgroundImage" json:"backgroundImage,omitempty"`
	Sort            uint32 `protobuf:"varint,5,opt,name=sort" json:"sort,omitempty"`
}

func (m *CreateCardRequest) Reset()                    { *m = CreateCardRequest{} }
func (m *CreateCardRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCardRequest) ProtoMessage()               {}
func (*CreateCardRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateCardRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *CreateCardRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCardRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateCardRequest) GetBackgroundImage() string {
	if m != nil {
		return m.BackgroundImage
	}
	return ""
}

func (m *CreateCardRequest) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

type CreateCardReply struct {
	Err    *Error `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	CardId uint64 `protobuf:"varint,2,opt,name=cardId" json:"cardId,omitempty"`
}

func (m *CreateCardReply) Reset()                    { *m = CreateCardReply{} }
func (m *CreateCardReply) String() string            { return proto.CompactTextString(m) }
func (*CreateCardReply) ProtoMessage()               {}
func (*CreateCardReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateCardReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *CreateCardReply) GetCardId() uint64 {
	if m != nil {
		return m.CardId
	}
	return 0
}

type ModifyCardInformation struct {
	CardId          uint64 `protobuf:"varint,1,opt,name=cardId" json:"cardId,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description     string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	BackgroundImage string `protobuf:"bytes,4,opt,name=backgroundImage" json:"backgroundImage,omitempty"`
	Sort            uint32 `protobuf:"varint,5,opt,name=sort" json:"sort,omitempty"`
}

func (m *ModifyCardInformation) Reset()                    { *m = ModifyCardInformation{} }
func (m *ModifyCardInformation) String() string            { return proto.CompactTextString(m) }
func (*ModifyCardInformation) ProtoMessage()               {}
func (*ModifyCardInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ModifyCardInformation) GetCardId() uint64 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *ModifyCardInformation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModifyCardInformation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ModifyCardInformation) GetBackgroundImage() string {
	if m != nil {
		return m.BackgroundImage
	}
	return ""
}

func (m *ModifyCardInformation) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

type ModifyCardRequest struct {
	Card *ModifyCardInformation `protobuf:"bytes,1,opt,name=Card" json:"Card,omitempty"`
}

func (m *ModifyCardRequest) Reset()                    { *m = ModifyCardRequest{} }
func (m *ModifyCardRequest) String() string            { return proto.CompactTextString(m) }
func (*ModifyCardRequest) ProtoMessage()               {}
func (*ModifyCardRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ModifyCardRequest) GetCard() *ModifyCardInformation {
	if m != nil {
		return m.Card
	}
	return nil
}

type ModifyCardReply struct {
	Err    *Error `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	CardId uint64 `protobuf:"varint,2,opt,name=cardId" json:"cardId,omitempty"`
}

func (m *ModifyCardReply) Reset()                    { *m = ModifyCardReply{} }
func (m *ModifyCardReply) String() string            { return proto.CompactTextString(m) }
func (*ModifyCardReply) ProtoMessage()               {}
func (*ModifyCardReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ModifyCardReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *ModifyCardReply) GetCardId() uint64 {
	if m != nil {
		return m.CardId
	}
	return 0
}

type CardInformation struct {
	CardId          uint64             `protobuf:"varint,1,opt,name=cardId" json:"cardId,omitempty"`
	ShopId          uint64             `protobuf:"varint,2,opt,name=shopId" json:"shopId,omitempty"`
	Name            string             `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description     string             `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	BackgroundImage string             `protobuf:"bytes,5,opt,name=backgroundImage" json:"backgroundImage,omitempty"`
	Status          CardStatus         `protobuf:"varint,6,opt,name=status,enum=card.pkg.rpc.protos.CardStatus" json:"status,omitempty"`
	Sort            uint32             `protobuf:"varint,7,opt,name=sort" json:"sort,omitempty"`
	Items           []*ItemInformation `protobuf:"bytes,8,rep,name=items" json:"items,omitempty"`
	CreateTime      int64              `protobuf:"varint,9,opt,name=createTime" json:"createTime,omitempty"`
}

func (m *CardInformation) Reset()                    { *m = CardInformation{} }
func (m *CardInformation) String() string            { return proto.CompactTextString(m) }
func (*CardInformation) ProtoMessage()               {}
func (*CardInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CardInformation) GetCardId() uint64 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *CardInformation) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *CardInformation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CardInformation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CardInformation) GetBackgroundImage() string {
	if m != nil {
		return m.BackgroundImage
	}
	return ""
}

func (m *CardInformation) GetStatus() CardStatus {
	if m != nil {
		return m.Status
	}
	return CardStatus_All
}

func (m *CardInformation) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *CardInformation) GetItems() []*ItemInformation {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *CardInformation) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type ItemInformation struct {
	ItemId            uint64                   `protobuf:"varint,1,opt,name=itemId" json:"itemId,omitempty"`
	Name              string                   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description       string                   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Price             uint64                   `protobuf:"varint,4,opt,name=price" json:"price,omitempty"`
	RenewPrice        uint64                   `protobuf:"varint,5,opt,name=renewPrice" json:"renewPrice,omitempty"`
	ValidityPeriod    uint32                   `protobuf:"varint,6,opt,name=validityPeriod" json:"validityPeriod,omitempty"`
	Sort              uint32                   `protobuf:"varint,7,opt,name=sort" json:"sort,omitempty"`
	Coupons           []*ItemCouponInformation `protobuf:"bytes,8,rep,name=coupons" json:"coupons,omitempty"`
	FirstRebateRatio  uint32                   `protobuf:"varint,9,opt,name=FirstRebateRatio" json:"FirstRebateRatio,omitempty"`
	SecondRebateRatio uint32                   `protobuf:"varint,10,opt,name=SecondRebateRatio" json:"SecondRebateRatio,omitempty"`
	Goods             []*ItemGoodsInformation  `protobuf:"bytes,11,rep,name=goods" json:"goods,omitempty"`
}

func (m *ItemInformation) Reset()                    { *m = ItemInformation{} }
func (m *ItemInformation) String() string            { return proto.CompactTextString(m) }
func (*ItemInformation) ProtoMessage()               {}
func (*ItemInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ItemInformation) GetItemId() uint64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *ItemInformation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ItemInformation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ItemInformation) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ItemInformation) GetRenewPrice() uint64 {
	if m != nil {
		return m.RenewPrice
	}
	return 0
}

func (m *ItemInformation) GetValidityPeriod() uint32 {
	if m != nil {
		return m.ValidityPeriod
	}
	return 0
}

func (m *ItemInformation) GetSort() uint32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *ItemInformation) GetCoupons() []*ItemCouponInformation {
	if m != nil {
		return m.Coupons
	}
	return nil
}

func (m *ItemInformation) GetFirstRebateRatio() uint32 {
	if m != nil {
		return m.FirstRebateRatio
	}
	return 0
}

func (m *ItemInformation) GetSecondRebateRatio() uint32 {
	if m != nil {
		return m.SecondRebateRatio
	}
	return 0
}

func (m *ItemInformation) GetGoods() []*ItemGoodsInformation {
	if m != nil {
		return m.Goods
	}
	return nil
}

type ItemCouponInformation struct {
	CouponId    uint64 `protobuf:"varint,1,opt,name=couponId" json:"couponId,omitempty"`
	CouponCount uint64 `protobuf:"varint,2,opt,name=couponCount" json:"couponCount,omitempty"`
}

func (m *ItemCouponInformation) Reset()                    { *m = ItemCouponInformation{} }
func (m *ItemCouponInformation) String() string            { return proto.CompactTextString(m) }
func (*ItemCouponInformation) ProtoMessage()               {}
func (*ItemCouponInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ItemCouponInformation) GetCouponId() uint64 {
	if m != nil {
		return m.CouponId
	}
	return 0
}

func (m *ItemCouponInformation) GetCouponCount() uint64 {
	if m != nil {
		return m.CouponCount
	}
	return 0
}

type ItemGoodsInformation struct {
	// SKUId
	GoodsId    uint64   `protobuf:"varint,1,opt,name=goodsId" json:"goodsId,omitempty"`
	GoodsCount uint64   `protobuf:"varint,2,opt,name=goodsCount" json:"goodsCount,omitempty"`
	GoodsName  string   `protobuf:"bytes,3,opt,name=goodsName" json:"goodsName,omitempty"`
	SPUID      uint64   `protobuf:"varint,4,opt,name=SPUID" json:"SPUID,omitempty"`
	Images     []string `protobuf:"bytes,5,rep,name=images" json:"images,omitempty"`
}

func (m *ItemGoodsInformation) Reset()                    { *m = ItemGoodsInformation{} }
func (m *ItemGoodsInformation) String() string            { return proto.CompactTextString(m) }
func (*ItemGoodsInformation) ProtoMessage()               {}
func (*ItemGoodsInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ItemGoodsInformation) GetGoodsId() uint64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *ItemGoodsInformation) GetGoodsCount() uint64 {
	if m != nil {
		return m.GoodsCount
	}
	return 0
}

func (m *ItemGoodsInformation) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *ItemGoodsInformation) GetSPUID() uint64 {
	if m != nil {
		return m.SPUID
	}
	return 0
}

func (m *ItemGoodsInformation) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

type RemoveCardRequest struct {
	CardId uint64 `protobuf:"varint,1,opt,name=cardId" json:"cardId,omitempty"`
	ShopId uint64 `protobuf:"varint,2,opt,name=shopId" json:"shopId,omitempty"`
}

func (m *RemoveCardRequest) Reset()                    { *m = RemoveCardRequest{} }
func (m *RemoveCardRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveCardRequest) ProtoMessage()               {}
func (*RemoveCardRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *RemoveCardRequest) GetCardId() uint64 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *RemoveCardRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type RemoveCardReply struct {
	Err *Error `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *RemoveCardReply) Reset()                    { *m = RemoveCardReply{} }
func (m *RemoveCardReply) String() string            { return proto.CompactTextString(m) }
func (*RemoveCardReply) ProtoMessage()               {}
func (*RemoveCardReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RemoveCardReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type SetCardItemsRequest struct {
	CardId uint64             `protobuf:"varint,1,opt,name=cardId" json:"cardId,omitempty"`
	Items  []*ItemInformation `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *SetCardItemsRequest) Reset()                    { *m = SetCardItemsRequest{} }
func (m *SetCardItemsRequest) String() string            { return proto.CompactTextString(m) }
func (*SetCardItemsRequest) ProtoMessage()               {}
func (*SetCardItemsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SetCardItemsRequest) GetCardId() uint64 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *SetCardItemsRequest) GetItems() []*ItemInformation {
	if m != nil {
		return m.Items
	}
	return nil
}

type SetCardItemsReply struct {
	CardId uint64             `protobuf:"varint,1,opt,name=cardId" json:"cardId,omitempty"`
	Items  []*ItemInformation `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	Err    *Error             `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
}

func (m *SetCardItemsReply) Reset()                    { *m = SetCardItemsReply{} }
func (m *SetCardItemsReply) String() string            { return proto.CompactTextString(m) }
func (*SetCardItemsReply) ProtoMessage()               {}
func (*SetCardItemsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *SetCardItemsReply) GetCardId() uint64 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *SetCardItemsReply) GetItems() []*ItemInformation {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *SetCardItemsReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type SetCardStatusRequest struct {
	CardId uint64     `protobuf:"varint,1,opt,name=cardId" json:"cardId,omitempty"`
	Status CardStatus `protobuf:"varint,2,opt,name=status,enum=card.pkg.rpc.protos.CardStatus" json:"status,omitempty"`
}

func (m *SetCardStatusRequest) Reset()                    { *m = SetCardStatusRequest{} }
func (m *SetCardStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*SetCardStatusRequest) ProtoMessage()               {}
func (*SetCardStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *SetCardStatusRequest) GetCardId() uint64 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *SetCardStatusRequest) GetStatus() CardStatus {
	if m != nil {
		return m.Status
	}
	return CardStatus_All
}

type SetCardStatusReply struct {
	Err    *Error `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	CardId uint64 `protobuf:"varint,2,opt,name=cardId" json:"cardId,omitempty"`
}

func (m *SetCardStatusReply) Reset()                    { *m = SetCardStatusReply{} }
func (m *SetCardStatusReply) String() string            { return proto.CompactTextString(m) }
func (*SetCardStatusReply) ProtoMessage()               {}
func (*SetCardStatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *SetCardStatusReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *SetCardStatusReply) GetCardId() uint64 {
	if m != nil {
		return m.CardId
	}
	return 0
}

type GetUserCardListRequest struct {
	UserId uint64 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	ShopId uint64 `protobuf:"varint,2,opt,name=shopId" json:"shopId,omitempty"`
}

func (m *GetUserCardListRequest) Reset()                    { *m = GetUserCardListRequest{} }
func (m *GetUserCardListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserCardListRequest) ProtoMessage()               {}
func (*GetUserCardListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *GetUserCardListRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserCardListRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type GetUserCardListReply struct {
	Err          *Error      `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	UserCardList []*UserCard `protobuf:"bytes,2,rep,name=userCardList" json:"userCardList,omitempty"`
}

func (m *GetUserCardListReply) Reset()                    { *m = GetUserCardListReply{} }
func (m *GetUserCardListReply) String() string            { return proto.CompactTextString(m) }
func (*GetUserCardListReply) ProtoMessage()               {}
func (*GetUserCardListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *GetUserCardListReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *GetUserCardListReply) GetUserCardList() []*UserCard {
	if m != nil {
		return m.UserCardList
	}
	return nil
}

type UserCard struct {
	CardId     uint64 `protobuf:"varint,1,opt,name=cardId" json:"cardId,omitempty"`
	ExpireTime uint32 `protobuf:"varint,2,opt,name=ExpireTime" json:"ExpireTime,omitempty"`
}

func (m *UserCard) Reset()                    { *m = UserCard{} }
func (m *UserCard) String() string            { return proto.CompactTextString(m) }
func (*UserCard) ProtoMessage()               {}
func (*UserCard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *UserCard) GetCardId() uint64 {
	if m != nil {
		return m.CardId
	}
	return 0
}

func (m *UserCard) GetExpireTime() uint32 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func init() {
	proto.RegisterType((*GetCardRequest)(nil), "card.pkg.rpc.protos.GetCardRequest")
	proto.RegisterType((*GetCardReply)(nil), "card.pkg.rpc.protos.GetCardReply")
	proto.RegisterType((*GetCardListRequest)(nil), "card.pkg.rpc.protos.GetCardListRequest")
	proto.RegisterType((*GetCardListReply)(nil), "card.pkg.rpc.protos.GetCardListReply")
	proto.RegisterType((*CreateCardRequest)(nil), "card.pkg.rpc.protos.CreateCardRequest")
	proto.RegisterType((*CreateCardReply)(nil), "card.pkg.rpc.protos.CreateCardReply")
	proto.RegisterType((*ModifyCardInformation)(nil), "card.pkg.rpc.protos.ModifyCardInformation")
	proto.RegisterType((*ModifyCardRequest)(nil), "card.pkg.rpc.protos.ModifyCardRequest")
	proto.RegisterType((*ModifyCardReply)(nil), "card.pkg.rpc.protos.ModifyCardReply")
	proto.RegisterType((*CardInformation)(nil), "card.pkg.rpc.protos.CardInformation")
	proto.RegisterType((*ItemInformation)(nil), "card.pkg.rpc.protos.ItemInformation")
	proto.RegisterType((*ItemCouponInformation)(nil), "card.pkg.rpc.protos.ItemCouponInformation")
	proto.RegisterType((*ItemGoodsInformation)(nil), "card.pkg.rpc.protos.ItemGoodsInformation")
	proto.RegisterType((*RemoveCardRequest)(nil), "card.pkg.rpc.protos.RemoveCardRequest")
	proto.RegisterType((*RemoveCardReply)(nil), "card.pkg.rpc.protos.RemoveCardReply")
	proto.RegisterType((*SetCardItemsRequest)(nil), "card.pkg.rpc.protos.SetCardItemsRequest")
	proto.RegisterType((*SetCardItemsReply)(nil), "card.pkg.rpc.protos.SetCardItemsReply")
	proto.RegisterType((*SetCardStatusRequest)(nil), "card.pkg.rpc.protos.SetCardStatusRequest")
	proto.RegisterType((*SetCardStatusReply)(nil), "card.pkg.rpc.protos.SetCardStatusReply")
	proto.RegisterType((*GetUserCardListRequest)(nil), "card.pkg.rpc.protos.GetUserCardListRequest")
	proto.RegisterType((*GetUserCardListReply)(nil), "card.pkg.rpc.protos.GetUserCardListReply")
	proto.RegisterType((*UserCard)(nil), "card.pkg.rpc.protos.UserCard")
	proto.RegisterEnum("card.pkg.rpc.protos.CardStatus", CardStatus_name, CardStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CardController service

type CardControllerClient interface {
	// 获取权益卡详情
	GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*GetCardReply, error)
	// 获取权益卡列表
	GetCardList(ctx context.Context, in *GetCardListRequest, opts ...grpc.CallOption) (*GetCardListReply, error)
	// 创建权益卡
	CreateCard(ctx context.Context, in *CreateCardRequest, opts ...grpc.CallOption) (*CreateCardReply, error)
	// 修改权益卡
	ModifyCard(ctx context.Context, in *ModifyCardRequest, opts ...grpc.CallOption) (*ModifyCardReply, error)
	// 删除权益卡
	RemoveCard(ctx context.Context, in *RemoveCardRequest, opts ...grpc.CallOption) (*RemoveCardReply, error)
	// 设置权益卡的选项列表
	SetCardItems(ctx context.Context, in *SetCardItemsRequest, opts ...grpc.CallOption) (*SetCardItemsReply, error)
	// 设置权益卡状态
	SetCardStatus(ctx context.Context, in *SetCardStatusRequest, opts ...grpc.CallOption) (*SetCardStatusReply, error)
	// 获取用户权益卡
	GetUserCardList(ctx context.Context, in *GetUserCardListRequest, opts ...grpc.CallOption) (*GetUserCardListReply, error)
}

type cardControllerClient struct {
	cc *grpc.ClientConn
}

func NewCardControllerClient(cc *grpc.ClientConn) CardControllerClient {
	return &cardControllerClient{cc}
}

func (c *cardControllerClient) GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*GetCardReply, error) {
	out := new(GetCardReply)
	err := grpc.Invoke(ctx, "/card.pkg.rpc.protos.CardController/GetCard", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardControllerClient) GetCardList(ctx context.Context, in *GetCardListRequest, opts ...grpc.CallOption) (*GetCardListReply, error) {
	out := new(GetCardListReply)
	err := grpc.Invoke(ctx, "/card.pkg.rpc.protos.CardController/GetCardList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardControllerClient) CreateCard(ctx context.Context, in *CreateCardRequest, opts ...grpc.CallOption) (*CreateCardReply, error) {
	out := new(CreateCardReply)
	err := grpc.Invoke(ctx, "/card.pkg.rpc.protos.CardController/CreateCard", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardControllerClient) ModifyCard(ctx context.Context, in *ModifyCardRequest, opts ...grpc.CallOption) (*ModifyCardReply, error) {
	out := new(ModifyCardReply)
	err := grpc.Invoke(ctx, "/card.pkg.rpc.protos.CardController/ModifyCard", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardControllerClient) RemoveCard(ctx context.Context, in *RemoveCardRequest, opts ...grpc.CallOption) (*RemoveCardReply, error) {
	out := new(RemoveCardReply)
	err := grpc.Invoke(ctx, "/card.pkg.rpc.protos.CardController/RemoveCard", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardControllerClient) SetCardItems(ctx context.Context, in *SetCardItemsRequest, opts ...grpc.CallOption) (*SetCardItemsReply, error) {
	out := new(SetCardItemsReply)
	err := grpc.Invoke(ctx, "/card.pkg.rpc.protos.CardController/SetCardItems", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardControllerClient) SetCardStatus(ctx context.Context, in *SetCardStatusRequest, opts ...grpc.CallOption) (*SetCardStatusReply, error) {
	out := new(SetCardStatusReply)
	err := grpc.Invoke(ctx, "/card.pkg.rpc.protos.CardController/SetCardStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardControllerClient) GetUserCardList(ctx context.Context, in *GetUserCardListRequest, opts ...grpc.CallOption) (*GetUserCardListReply, error) {
	out := new(GetUserCardListReply)
	err := grpc.Invoke(ctx, "/card.pkg.rpc.protos.CardController/GetUserCardList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CardController service

type CardControllerServer interface {
	// 获取权益卡详情
	GetCard(context.Context, *GetCardRequest) (*GetCardReply, error)
	// 获取权益卡列表
	GetCardList(context.Context, *GetCardListRequest) (*GetCardListReply, error)
	// 创建权益卡
	CreateCard(context.Context, *CreateCardRequest) (*CreateCardReply, error)
	// 修改权益卡
	ModifyCard(context.Context, *ModifyCardRequest) (*ModifyCardReply, error)
	// 删除权益卡
	RemoveCard(context.Context, *RemoveCardRequest) (*RemoveCardReply, error)
	// 设置权益卡的选项列表
	SetCardItems(context.Context, *SetCardItemsRequest) (*SetCardItemsReply, error)
	// 设置权益卡状态
	SetCardStatus(context.Context, *SetCardStatusRequest) (*SetCardStatusReply, error)
	// 获取用户权益卡
	GetUserCardList(context.Context, *GetUserCardListRequest) (*GetUserCardListReply, error)
}

func RegisterCardControllerServer(s *grpc.Server, srv CardControllerServer) {
	s.RegisterService(&_CardController_serviceDesc, srv)
}

func _CardController_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardControllerServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.pkg.rpc.protos.CardController/GetCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardControllerServer).GetCard(ctx, req.(*GetCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardController_GetCardList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardControllerServer).GetCardList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.pkg.rpc.protos.CardController/GetCardList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardControllerServer).GetCardList(ctx, req.(*GetCardListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardController_CreateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardControllerServer).CreateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.pkg.rpc.protos.CardController/CreateCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardControllerServer).CreateCard(ctx, req.(*CreateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardController_ModifyCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardControllerServer).ModifyCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.pkg.rpc.protos.CardController/ModifyCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardControllerServer).ModifyCard(ctx, req.(*ModifyCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardController_RemoveCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardControllerServer).RemoveCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.pkg.rpc.protos.CardController/RemoveCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardControllerServer).RemoveCard(ctx, req.(*RemoveCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardController_SetCardItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCardItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardControllerServer).SetCardItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.pkg.rpc.protos.CardController/SetCardItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardControllerServer).SetCardItems(ctx, req.(*SetCardItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardController_SetCardStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCardStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardControllerServer).SetCardStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.pkg.rpc.protos.CardController/SetCardStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardControllerServer).SetCardStatus(ctx, req.(*SetCardStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardController_GetUserCardList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCardListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardControllerServer).GetUserCardList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.pkg.rpc.protos.CardController/GetUserCardList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardControllerServer).GetUserCardList(ctx, req.(*GetUserCardListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CardController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "card.pkg.rpc.protos.CardController",
	HandlerType: (*CardControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCard",
			Handler:    _CardController_GetCard_Handler,
		},
		{
			MethodName: "GetCardList",
			Handler:    _CardController_GetCardList_Handler,
		},
		{
			MethodName: "CreateCard",
			Handler:    _CardController_CreateCard_Handler,
		},
		{
			MethodName: "ModifyCard",
			Handler:    _CardController_ModifyCard_Handler,
		},
		{
			MethodName: "RemoveCard",
			Handler:    _CardController_RemoveCard_Handler,
		},
		{
			MethodName: "SetCardItems",
			Handler:    _CardController_SetCardItems_Handler,
		},
		{
			MethodName: "SetCardStatus",
			Handler:    _CardController_SetCardStatus_Handler,
		},
		{
			MethodName: "GetUserCardList",
			Handler:    _CardController_GetUserCardList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "card.proto",
}

func init() { proto.RegisterFile("card.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1063 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0x4f, 0x8f, 0xdb, 0x44,
	0x14, 0xaf, 0xe3, 0xfc, 0x7d, 0xd9, 0xdd, 0x24, 0xb3, 0x69, 0x65, 0x59, 0x50, 0x82, 0x29, 0xdb,
	0xec, 0xb2, 0xda, 0xc3, 0x72, 0x40, 0xe2, 0x40, 0x69, 0xb3, 0x65, 0x89, 0x04, 0xd5, 0xca, 0x61,
	0x41, 0xaa, 0x90, 0x2a, 0xaf, 0x3d, 0x4d, 0xad, 0x8d, 0x3d, 0x66, 0x3c, 0x69, 0x59, 0xbe, 0x00,
	0x17, 0xae, 0x48, 0x1c, 0x90, 0x38, 0x70, 0xe7, 0xc0, 0x9d, 0x2f, 0xc0, 0xa7, 0x42, 0x33, 0x63,
	0xc7, 0x13, 0xc7, 0xde, 0x4d, 0x4a, 0x11, 0xa7, 0xcc, 0x7b, 0xf3, 0xfe, 0xcd, 0xef, 0xfd, 0xf1,
	0x0b, 0x80, 0xeb, 0x50, 0xef, 0x28, 0xa2, 0x84, 0x11, 0xb4, 0x2b, 0xcf, 0x97, 0xd3, 0x23, 0x1a,
	0xb9, 0x92, 0x17, 0x9b, 0x3d, 0xce, 0x7c, 0xe6, 0x92, 0x20, 0x20, 0xa1, 0xe4, 0x59, 0x9f, 0xc2,
	0xce, 0x29, 0x66, 0x23, 0x87, 0x7a, 0x36, 0xfe, 0x6e, 0x8e, 0x63, 0x86, 0xee, 0x40, 0x9d, 0x8b,
	0x8d, 0x3d, 0x43, 0x1b, 0x68, 0xc3, 0xaa, 0x9d, 0x50, 0x9c, 0x1f, 0xbf, 0x20, 0xd1, 0xd8, 0x33,
	0x2a, 0x92, 0x2f, 0x29, 0xeb, 0x27, 0x0d, 0xb6, 0x16, 0x26, 0xa2, 0xd9, 0x15, 0x3a, 0x04, 0x1d,
	0x53, 0x2a, 0xb4, 0xdb, 0xc7, 0xe6, 0x51, 0x41, 0x20, 0x47, 0x8f, 0x29, 0x25, 0xd4, 0xe6, 0x62,
	0xe8, 0x09, 0x74, 0x84, 0x83, 0xf0, 0x39, 0xa1, 0x81, 0xc3, 0x7c, 0x12, 0x0a, 0xfb, 0xed, 0xe3,
	0x7b, 0x85, 0x9a, 0xa3, 0x65, 0x59, 0x3b, 0xaf, 0x6c, 0xfd, 0xa5, 0x01, 0x4a, 0xc2, 0xf9, 0xc2,
	0x8f, 0x99, 0xf2, 0xaa, 0x24, 0x7a, 0x4d, 0x8d, 0x1e, 0x7d, 0x04, 0xf5, 0x98, 0x39, 0x6c, 0x1e,
	0x0b, 0xaf, 0x3b, 0xc7, 0xef, 0x94, 0x7a, 0x9d, 0x08, 0x31, 0x3b, 0x11, 0x47, 0x08, 0xaa, 0x91,
	0x33, 0xc5, 0x86, 0x2e, 0xcc, 0x89, 0x33, 0x32, 0xa1, 0xc9, 0x7f, 0x27, 0xfe, 0x0f, 0xd8, 0xa8,
	0x0a, 0xfe, 0x82, 0x46, 0x7b, 0xb0, 0xf3, 0xca, 0x67, 0x2f, 0xc6, 0x0c, 0x07, 0x27, 0x98, 0x39,
	0xfe, 0xcc, 0xa8, 0x0d, 0xb4, 0x61, 0xd3, 0xce, 0x71, 0xad, 0x3f, 0x34, 0xe8, 0x2e, 0xc5, 0xbf,
	0x39, 0xa4, 0x5f, 0xc3, 0x6e, 0x0e, 0x15, 0x6e, 0xc9, 0xa8, 0x0c, 0xf4, 0xb5, 0x61, 0x2d, 0x32,
	0x80, 0xfa, 0x50, 0x73, 0xc9, 0x3c, 0x64, 0xc9, 0x9b, 0x25, 0x61, 0xfd, 0xa6, 0x41, 0x6f, 0x44,
	0xb1, 0xc3, 0x70, 0xae, 0x8a, 0x0a, 0xf1, 0x46, 0x50, 0x0d, 0x9d, 0x00, 0x0b, 0xb4, 0x5b, 0xb6,
	0x38, 0xa3, 0x01, 0xb4, 0x3d, 0x1c, 0xbb, 0xd4, 0x8f, 0x44, 0xfa, 0x75, 0x71, 0xa5, 0xb2, 0xd0,
	0x10, 0x3a, 0x17, 0x8e, 0x7b, 0x39, 0xa5, 0x64, 0x1e, 0x7a, 0xe3, 0x80, 0xe3, 0x5e, 0x15, 0x52,
	0x79, 0x36, 0xb7, 0x1f, 0x13, 0xca, 0x04, 0xb8, 0xdb, 0xb6, 0x38, 0x5b, 0xdf, 0x40, 0x47, 0x0d,
	0x70, 0x73, 0x40, 0xb3, 0x96, 0xa8, 0xa8, 0x2d, 0x61, 0xfd, 0xae, 0xc1, 0xed, 0x2f, 0x89, 0xe7,
	0x3f, 0xbf, 0xca, 0xe1, 0x57, 0xda, 0x44, 0xff, 0xc7, 0xf3, 0x27, 0xd0, 0xcb, 0x82, 0x4c, 0xf3,
	0xf3, 0x09, 0x54, 0x39, 0x99, 0x20, 0x70, 0x50, 0x88, 0x40, 0xe1, 0xd3, 0x6c, 0xa1, 0xc7, 0x31,
	0x55, 0x8d, 0xbe, 0x39, 0x4c, 0xff, 0xae, 0x40, 0x67, 0x5d, 0x34, 0x4b, 0x46, 0xd2, 0x02, 0x65,
	0xbd, 0x1c, 0xe5, 0xea, 0x5a, 0x28, 0xd7, 0x8a, 0x51, 0xce, 0x86, 0x46, 0x7d, 0xe3, 0xa1, 0x21,
	0xd2, 0xd3, 0xc8, 0xd2, 0x83, 0x3e, 0x86, 0x9a, 0xcf, 0x70, 0x10, 0x1b, 0xcd, 0x6b, 0xfa, 0x93,
	0x0f, 0x08, 0x35, 0x09, 0x52, 0x05, 0xdd, 0x05, 0x70, 0x45, 0x65, 0x7f, 0xe5, 0x07, 0xd8, 0x68,
	0x0d, 0xb4, 0xa1, 0x6e, 0x2b, 0x1c, 0xeb, 0x4f, 0x1d, 0x3a, 0x39, 0x55, 0x0e, 0x1a, 0x57, 0xce,
	0xc0, 0x94, 0xd4, 0x6b, 0x96, 0x66, 0x1f, 0x6a, 0x11, 0xf5, 0xdd, 0x74, 0xde, 0x49, 0x82, 0xc7,
	0x45, 0x71, 0x88, 0x5f, 0x9d, 0x89, 0xab, 0x9a, 0xb8, 0x52, 0x38, 0x7c, 0x18, 0xbe, 0x74, 0x66,
	0xbe, 0xe7, 0xb3, 0xab, 0x33, 0x4c, 0x7d, 0xe2, 0x09, 0x20, 0xb7, 0xed, 0x1c, 0xb7, 0x10, 0xaf,
	0x13, 0x68, 0xb8, 0x64, 0x1e, 0x91, 0x30, 0x45, 0xec, 0xa0, 0x14, 0xb1, 0x91, 0x90, 0x53, 0x71,
	0x4b, 0x55, 0xd1, 0x01, 0x74, 0x3f, 0xf3, 0x29, 0x9f, 0xaf, 0x17, 0x0e, 0xc3, 0x36, 0xbf, 0x15,
	0xf8, 0x6d, 0xdb, 0x2b, 0x7c, 0x74, 0x08, 0xbd, 0x09, 0x76, 0x49, 0xe8, 0xa9, 0xc2, 0x20, 0x84,
	0x57, 0x2f, 0xd0, 0x03, 0xa8, 0x4d, 0x09, 0xf1, 0x62, 0xa3, 0x2d, 0xa2, 0xdb, 0x2f, 0x8d, 0xee,
	0x94, 0x4b, 0x2d, 0x25, 0x55, 0xe8, 0x59, 0xe7, 0x70, 0xbb, 0x30, 0x78, 0xfe, 0x79, 0x91, 0xe1,
	0x2f, 0x72, 0xb7, 0xa0, 0x79, 0xa6, 0xe4, 0x79, 0x24, 0x26, 0xb4, 0xec, 0x07, 0x95, 0x65, 0xfd,
	0xaa, 0x41, 0xbf, 0xc8, 0x2d, 0x32, 0xa0, 0x21, 0x1c, 0x2f, 0xac, 0xa6, 0x24, 0x4f, 0xa3, 0x38,
	0xaa, 0x36, 0x15, 0x0e, 0x7a, 0x0b, 0x5a, 0x82, 0x7a, 0x92, 0x35, 0x5b, 0xc6, 0xe0, 0xa5, 0x31,
	0x39, 0x3b, 0x1f, 0x9f, 0xa4, 0xa5, 0x21, 0x08, 0x51, 0x7e, 0xbc, 0x89, 0x62, 0xa3, 0x36, 0xd0,
	0x87, 0x2d, 0x3b, 0xa1, 0xac, 0x11, 0xf4, 0x6c, 0x1c, 0x90, 0x97, 0xf8, 0xdf, 0xec, 0x22, 0x0f,
	0xa0, 0xa3, 0x1a, 0xd9, 0x78, 0x2a, 0x59, 0x3e, 0xec, 0x4e, 0xe4, 0xc7, 0x97, 0x43, 0x15, 0xdf,
	0x14, 0xc7, 0xa2, 0x77, 0x2b, 0x1b, 0xf7, 0xae, 0xf5, 0xb3, 0xc6, 0xcb, 0x4a, 0xf5, 0xc5, 0xc3,
	0xfd, 0x0f, 0x3c, 0xa5, 0x10, 0xe8, 0xeb, 0x41, 0x30, 0x85, 0x7e, 0x12, 0x56, 0x32, 0xbc, 0x6e,
	0xc0, 0xe0, 0x75, 0x37, 0x28, 0xeb, 0x29, 0xa0, 0x9c, 0xa3, 0x37, 0xf7, 0x15, 0xf9, 0x1c, 0xee,
	0x9c, 0x62, 0x76, 0x1e, 0x63, 0x5a, 0xb0, 0x08, 0xce, 0x63, 0x4c, 0xb3, 0x67, 0x48, 0xaa, 0xb4,
	0xa4, 0x7e, 0xd4, 0xa0, 0xbf, 0x62, 0x6a, 0xf3, 0x40, 0x1f, 0xc2, 0xd6, 0x5c, 0x31, 0x91, 0xa4,
	0xf1, 0xed, 0x42, 0xb5, 0xd4, 0x97, 0xbd, 0xa4, 0x62, 0x3d, 0x82, 0x66, 0x7a, 0x53, 0x9a, 0x8c,
	0xbb, 0x00, 0x8f, 0xbf, 0x8f, 0x7c, 0x2a, 0x3f, 0x08, 0x15, 0x31, 0xa3, 0x14, 0xce, 0xc1, 0x21,
	0x40, 0x06, 0x38, 0x6a, 0x80, 0xfe, 0x70, 0x36, 0xeb, 0xde, 0x42, 0x00, 0xf5, 0xf3, 0x70, 0x1e,
	0x63, 0xaf, 0xab, 0xa1, 0x16, 0xd4, 0xc6, 0xfc, 0xdc, 0xad, 0x1c, 0xff, 0x52, 0x87, 0x1d, 0x2e,
	0x3e, 0x22, 0x21, 0xa3, 0x64, 0x36, 0xc3, 0x14, 0x4d, 0xa0, 0x91, 0x6c, 0xa7, 0xe8, 0xbd, 0xc2,
	0xe0, 0x97, 0xff, 0x4d, 0x98, 0xef, 0x5e, 0x2f, 0x14, 0xcd, 0xae, 0xac, 0x5b, 0xe8, 0x19, 0xb4,
	0x95, 0x95, 0x17, 0xdd, 0xbf, 0x4e, 0x47, 0xc9, 0xa5, 0xf9, 0xfe, 0xcd, 0x82, 0xd2, 0xc1, 0xb7,
	0x00, 0xd9, 0x06, 0x88, 0xf6, 0x8a, 0x2b, 0x34, 0xbf, 0xc3, 0x9a, 0xf7, 0x6e, 0x94, 0x5b, 0x58,
	0xcf, 0x76, 0xa1, 0x12, 0xeb, 0x2b, 0x1b, 0x58, 0x89, 0xf5, 0xdc, 0x52, 0x25, 0xad, 0x67, 0x33,
	0xad, 0xc4, 0xfa, 0xca, 0xe4, 0x2c, 0xb1, 0x9e, 0x1b, 0x8e, 0xd6, 0x2d, 0x74, 0x01, 0x5b, 0xea,
	0x10, 0x42, 0xc3, 0x42, 0xbd, 0x82, 0x99, 0x68, 0xee, 0xad, 0x21, 0x29, 0x7d, 0x60, 0xd8, 0x5e,
	0x6a, 0x74, 0xb4, 0x7f, 0x9d, 0xea, 0xd2, 0xd4, 0x31, 0xef, 0xaf, 0x23, 0x2a, 0xdd, 0x5c, 0x42,
	0x27, 0xd7, 0xa8, 0xe8, 0x83, 0xb2, 0x02, 0x29, 0x98, 0x0c, 0xe6, 0xfe, 0x7a, 0xc2, 0xc2, 0xd9,
	0xa3, 0xe6, 0xd3, 0xba, 0x14, 0xb8, 0x90, 0xbf, 0x1f, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x4c,
	0xaf, 0x94, 0xaa, 0x7e, 0x0f, 0x00, 0x00,
}
