rpc:
  enable: true
  ip: 127.0.0.1
  port: 8088
log:
  level: debug
mysql:
  common:
    host: 127.0.0.1
    port: 3306
    username: root
    password:
    database: fanli_card
redis:
  common:
    host: 127.0.0.1
    port: 6379
rpcServices:
  coupon:
    host: 127.0.0.1
    port: 8092
    connectTimeout: 3s
  rebate:
    host: 127.0.0.1
    port: 8099
    connectTimeout: 3s
  goods:
    host: 127.0.0.1
    port: 8089
    connectTimeout: 1s
  order:
    host: 127.0.0.1
    port: 8096
    connectTimeout: 3s